import { NextResponse } from "next/server";
import type { Plan } from "@/lib/types";

const plans: Plan[] = [
  {
    id: "b2c-puntual",
    name: "B2C Puntual",
    badge: "B2C",
    description:
      "Para propietarios individuales que necesitan valuaciones profesionales de sus propiedades comerciales",
    customerType: "Propietario individual",
    periodicity: "monthly",
    priceMonthly: 199,
    priceAnnual: null,
    priceOneTime: null,
    maxValuations: 10,
    maxProperties: 20,
    valuationPeriod: "month",
    extraValuationPrice: null,
    maxUsers: 2,
    supportLevel: "Email",
    features: [
      "10 valuaciones / mes con IA",
      "Reporte PDF profesional",
      "Análisis de comparables",
      "Factores de riesgo",
      "Mapa geolocalizado",
      "Dashboard básico",
    ],
    isActive: true,
    priceTiers: [
      {
        label: "Básico",
        price: "$199",
        features: [
          "10 valuaciones / mes",
          "Reporte PDF estándar",
          "Análisis de comparables",
          "Mapa geolocalizado",
        ],
      },
      {
        label: "Premium",
        price: "$399",
        features: [
          "10 valuaciones / mes",
          "Reporte PDF premium detallado",
          "Análisis de comparables avanzados",
          "Factores de riesgo completos",
          "Mapa geolocalizado con heatmap",
          "Soporte por email prioritario",
          "2 usuarios incluidos",
        ],
      },
    ],
  },
  {
    id: "b2b-basico",
    name: "B2B Básico",
    badge: "B2B",
    description: "Para peritos independientes o pequeñas agencias inmobiliarias",
    customerType: "Avaluador / agencia pequeña",
    periodicity: "annual",
    priceMonthly: 825,
    priceAnnual: 9900,
    priceOneTime: null,
    maxValuations: 50,
    maxProperties: 100,
    valuationPeriod: "year",
    extraValuationPrice: 120,
    maxUsers: 3,
    supportLevel: "Email 48h",
    features: [
      "50 valuaciones / año",
      "Dashboard avanzado",
      "Análisis de mercado",
      "Reportes PDF ilimitados",
      "Mapa de propiedades",
      "Importar / exportar CSV",
      "Hasta 3 usuarios con roles",
    ],
    isActive: true,
  },
  {
    id: "b2b-pro",
    name: "B2B Pro",
    badge: "B2B",
    description: "Para bancos regionales o fondos de inversión medianos",
    customerType: "Banco regional / fondo mediano",
    periodicity: "annual",
    priceMonthly: 1658,
    priceAnnual: 19900,
    priceOneTime: null,
    maxValuations: 200,
    maxProperties: 500,
    valuationPeriod: "year",
    extraValuationPrice: 90,
    maxUsers: 10,
    supportLevel: "Chat + Email 24h",
    features: [
      "200 valuaciones / año",
      "Todo lo de B2B Básico",
      "Hasta 10 usuarios con roles",
      "API de integración",
      "Comparables avanzados",
      "Heatmap de mercado",
      "Soporte prioritario 24h",
    ],
    isActive: true,
    highlighted: true,
  },
  {
    id: "b2b-enterprise",
    name: "B2B Enterprise",
    badge: "B2B",
    description: "Solución completa para bancos grandes y aseguradoras",
    customerType: "Banco grande / aseguradora",
    periodicity: "multiyear",
    priceMonthly: null,
    priceAnnual: 39900,
    priceOneTime: null,
    maxValuations: -1,
    maxProperties: -1,
    valuationPeriod: "year",
    extraValuationPrice: null,
    maxUsers: -1,
    supportLevel: "CSM + SLA 4h",
    features: [
      "Valuaciones ilimitadas",
      "Todo lo de B2B Pro",
      "Usuarios ilimitados + SSO",
      "API dedicada con SLA",
      "Integración CRM",
      "Facturación electrónica (CFDI)",
      "Customer Success Manager",
      "SLA de respuesta 4 horas",
      "Contrato multi-año",
    ],
    isActive: true,
  },
];

export async function GET() {
  return NextResponse.json({ plans });
}
